version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/dom-crawler
    versions:
    - 4.4.18
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.18
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.18
