filter:
  paths:
    - 'app/*'
checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: false
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
  javascript: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 2
  php_analyzer: true
  php_mess_detector: true
  php_changetracking: true
  php_code_coverage: false
  php_code_sniffer:
    config:
      standard: PSR2
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests]
build:
  environment:
    hosts:
      localhost: 127.0.0.1
    apache2:
      sites:
        laravel_app:
          web_root: public/
          host: localhost
    selenium:
      version: 3.0
      chrome_driver_version: 2.27
    php:
      version: 7.1
  tests:
    stop_on_failure: true
    before:
      - composer self-update
      - composer install --prefer-source --no-interaction
    override:
      -
        command: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
        coverage:
          file: coverage.clover
          format: php-clover