language: php
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - google-chrome-stable

php:
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - composer self-update
  - composer install --prefer-source --no-interaction

before_install:
  - pip install --user codecov

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - codecov
