language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
    allow_failures:
        - php: 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mysql -e 'create database forge;'
  - php artisan migrate --env="testing"
  - php artisan db:seed --env="testing"

script:
  - vendor/bin/phpunit

notifications:
email: false
pushover:
  api_key: WDikzXE4XeJzyhfH53vL69S0Aq/UleqxAp8/QSchqlYkjuE034jScmilC/5hs2AdBPmf6JHV3BcioK2dccw0fUgFQmk84vuQU/CaWlJdaEPcI/CKT7Yjqz9VbuDVVdg3JnFDC+WMktCOtsFj9ZrhJLYOwbSJpfzfDeBuP7GBERB7rwPwHJMyV7JVgFCRAWPDFFu482mXcNOa9NxqchqTP9ZZgbeZ2sHYshTjCG8VGb8b8YuGJi1NNxpsgS2apITqonU3rjqehM9Jtfh/ReEXHa6W+7gzQ2od2gsP24UFAguhL1Wk52XjfNVsnq9bVWhVyA1bMzmK/yv68Y5XyION+otEJMijcfric3SF8sIcnYruoaSkVcgo5zRHpD1jfKrE02GFRvU0aug7BF6sNOftJGtCDscPDRuik+GxShqNEymZIHp9T8VRkV0k94IPV5PgJHbJQ4uO9qeCPWFBqeAM713QLNPkriTcUT3+nHPaLk1pVjdQyysqMhdPdphGbbwwfZzL1E8l/4xULSk4uGO8mbxtk7PpVrkdmrT85rTJdWoDlHdRJo/XWWi63pKJ5BaibVcVk7fkESKBJgFxzM29yT+AAO0ph8OgPmNiY0YjbrdplP7yR2QXssroUhuI5zJ0WI3vbWkcrw3DtZQSlsKKdUKz6Szqoo/66xqor70p4+E=
  users:
    - gqdqLGL003NZFfQ6puiGu3klIG58LZCZkJ3bHcKKpuKjL17ztd49PDC0iKVBbu/NFhKSKtD4R5LvihbUn44zmIFtTMyJoTnEB4HjFrpDq+y3ZPkF6R8A9ug7HLr7+6tu+rozYKJ/G3nTpOJFNV3QU++F85zzJC8WkEDRSaiCOt7YgRN5DZSmFK7feDwTD8iee1NLBhY+0nwMnruNzE140ZLevFfZEsDETdiXeLEOiLFIZtdGj3pnGo/+98sTWSNRtUTXsuaKPChC93gWmCxnesMN6txkyw98hFLJ5xb59dKqwmYR+O7AaEDlYZSxSSwqYwCPqDov5Ja/UE2Fu9AS3JQ7I6RIEdkvPzJLy5LgMuW2Ko1dwLO2DT6g4dRAxUsoYrl2MoatYdJnAsp/germCvAVBLZO/qM2YjW76zV9ubtbEz596geJZTvSSgr+2MXWuU2QXu/J4rzPUhbdWRxr27gAM1NqAmFwvq6tfGUtVQSveLq7GxL2OTIAXqIlQ5NYC/kzgfKyHyCT7AQ7XKBNfClyLjhmWIe4zKLZ50jhqRXUwbdF9Cf3EHAodSWnrBS0BeVer0yo6W0Qn80j1EaZYl+2bbTsVEnXHvWL17JZ9TfbIWRMiN4na7EIYbKxCZcPdycE1BXUHkcXIEjyNAg5jHb/d3fXGpuSzTXGOoPXomg=
