language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - setup=basic

matrix:
    allow_failures:
        - php: 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

before_install:
  - pip install --user codecov

after_success:
  - codecov

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
