language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - setup=basic

matrix:
    allow_failures:
        - php: 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mysql -e 'create database forge;'
  - php artisan migrate --env="testing"
  - php artisan db:seed --env="testing"

before_install:
  - pip install --user codecov

after_success:
  - codecov

script:
  - vendor/bin/phpunit
