language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
    allow_failures:
        - php: 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mysql -e 'create database forge;'
  - php artisan migrate --env="testing"
  - php artisan db:seed --env="testing"

script:
  - vendor/bin/phpunit

notifications:
email: false
pushover:
  api_key: MfSPQHmeufKb4uX7H7CzKTLPYirfiU5gm9OfOTcPfpyM650TH2Ov/Buysrf0sflDVOx140LuNipP0JgvG/+xjLsqMBmbA33GwPhv7iClchCU65Em6ye1PRBuqNyNI9QEB5cicuUgND/QGp43ua/mgUs2LUO3XAklWMSU5WTLM9mtMZUmw8lt8D3c69PIZw7KTzFFJZYBwmhbHkz76uJ06OBhBJ9rVyfbQHHj5QyROupaN2ZiLrGn0m2ZW/94BPcfuiTSZtdTtehg3Mn5mdgw/me7oQ8wPGnnOOdqTc4+jXC7BODde6GyWgWvoaYh5Q7+2SEt623VuxNGcJmuSJM63lh2FNUnoSZRelAMKAVwXFgEE1oNPiOmnb1cdsBEhhFSksT8+WHSaoAn9ewA/LsXGjnSP4xCpILCDZEnTIztxCuQpA1pRlCIq4bhAJ+7TwuDEq6OefpJnaHLb+X9g5ZciMGQSYorRmXtfMl8155brKkdJEPSC0yICYlzJ8JjMFnP0u+xkx0SHowg9gxNOwyZMpbiOJZldjX3HM7jViWg2FNtKk7e0xRSPe1XOzAenk23ELGvxo+orSc5Qif3csRXLNRxewQK2oJxBY1q4oywdQEsBCyWk/IOURkkV3jDKlhtofflCUGlvwb3juzmh/WjoE1zm2HbWYlZlhnicjVvORM=
  users:
    - WrcwIHdH9hyT8wGSUXxxkT12bm2GPAxocW778JL2UOPk7U4QbSOGjSCAsjzQ0zzU4Jj6xefv9ZApNyFXJqL592BJAN1BIbqrVxUrCgy41lS9SD+EZ//W936HIWs6M7+2BbfiEPNgwslXNhfd/hoZdjDQnmM8vPurZZ4J0FQNfwgncAw1mTI8JLPYaPv244ahS8x8oiC8lYuK48UTXaXOajcOSjpNBanoAZ2Iw9yMlu4cRS98vhjwVIhLckumRijnbFz3BetI9326hnWKaYtI7KVabOo6gqChRVcKuSMhBdFE28HJwQtzSxcW83U4ruGqj7ymO4T/TCXuv4eElyL2PlHuGf0O9oX6pQx81qX0IW1YOrsHBj+S68n8Rj4+XabdAZbnqdru9XXLpO0c9ySkIF5cDHKime5gMJuFE+0jnxzF+P4WtMEuEGIQT7kp+VlvY2ldVhREI6ABjYW/o4/B0XN6UBelHnM+E3QVA4C79vjxf8ariKKAc9iO5SgGPkYryizutVkjEQSPaZVg5qa/LQsqyniib3VsC4S0VI+qCiFPmU+I4GeobLImzRFlc+5Xj9OO0ocSHEYFLYKhBSAWQ/Ct7ATERRZUcIqjWEQo0Bb7y2AfUOpcAqij42rxnOIU0w2GkqQ5Fr4Wmi/UwANPfLOKwk3e7wr2rI4ZOQpv74I=
