language: php

php:
  - 7.0

env:
  global:
    - setup=basic

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

before_install:
  - pip install --user codecov

after_success:
  - codecov

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
